### ISSUE TITLE
Button Issue

### ISSUE THREAD

**Issue by TheAll3ycat** [Meowmaritus/WiitarThing#11]
Okay, I don't know what's happening to the program, it worked fine a while ago, but now (This happened after I had connected a Nintendo Switch Pro Controller to my Laptop) when I connect my Wii-mote to the program, it maps the Whammy Bar as the Mouse, the Green Key is simultaneously the Enter Key and the Green Key, and Red is the Red Key and Space. The buttons are all screwing up and I honestly cannot figure out how to fix this. I feel like it's the Switch Controllers fault. It really sucks not being able to play Clone Hero because this program worked extremely well before.

**Comment by TheAll3ycat** [comment]
Also to note, before it is saying it's connecting to an XInput and Xbox Controller afterwards so I don't know if that means anything.

**Comment by LanHikariDS** [comment]
It's likely that whatever setup you have for your Switch Pro Controller is also using the SCP driver, and overwrote WiitarThing's instance of SCP. Simple fix, just go into WiitarThing's "SCP_Driver" folder, run "ScpDriver.exe", have only "Configure Service" checked in ScpDriver's window, and hit install. Should work after that.

**Comment by TheAll3ycat** [comment]
I fixed it, I thought it WAS the Switch Controller support but it was just the Xbox support in Steam messing with my settings. It's fixed now!
