### ISSUE TITLE
sliding bar doesn't work  

### ISSUE THREAD

**Issue by Antobm81** [Meowmaritus/WiitarThing#2]
sliding bar doesn't work  pls help it worked once but it dosn't work now

**Comment by PipeRojas** [comment]
I´ve been in the same trouble using my GHWT guitar with dolphin emulator, and i solve this reconnecting the guitar arm from the guitar (if it´s possible with your guitar) or reconnecting the Wii Remote to the guitar while im playing with it. It worked for me and you should try it.
