### ISSUE TITLE
Wii GHWT Drums Support

### ISSUE THREAD

**Issue by PipeRojas** [Meowmaritus/WiitarThing#3]
Can u plz add drums Support for usage with clone hero!!!???

**Comment by CristobalPenaloza** [comment]
Hi @Meowmaritus , are you working currently on drums support?

Because I would love to help! I currently have a personal copy of your project on which I added drums support, which I use to play Clone Hero.

If you're not working currently on it, can I submit a pull request with my code?

**Comment by Meowmaritus** [comment]
@CristobalPenaloza I'm not currently doing anything on this so go ahead and submit a pull request. Could you make sure the readme is updated for drum related stuff if needed too?

**Comment by CristobalPenaloza** [comment]
@Meowmaritus Alright, I submited a pull request ready for review and updated the readme. #5

**Comment by elkyarypappa** [comment]
did you make it work with the new update? 
i have this model but it doesnt work, clone hero just doesnt detect when i press any button

![image](https://user-images.githubusercontent.com/65004065/81372917-c57e6a80-90b8-11ea-957d-989443d7da10.png)

**Comment by CristobalPenaloza** [comment]
It should work with that kind of model... @Meowmaritus , did you make a new release with the drums update?

Edit: Added a new release build in my fork. Hope it helps!
https://github.com/CristobalPenaloza/WiitarThing/releases

[WiitarThing.V2.8.zip](https://github.com/Meowmaritus/WiitarThing/files/4600192/WiitarThing.V2.8.zip)

**Comment by elkyarypappa** [comment]
@CristobalPenaloza the new build you just uploaded worked fine now :) so thank you so much, now my dreams are true

**Comment by Rirya** [comment]
i can't use 5 lane drums because in wiitarthing the green and the orange are the same button which is A and in clone hero i can't set up them
if i write something bad sorry
![IMG_20200822_011203](https://user-images.githubusercontent.com/54458117/90942120-b081d900-e414-11ea-9ef4-15440867e6ac.jpg)
![Annotazione 2020-08-22 010653](https://user-images.githubusercontent.com/54458117/90942122-b24b9c80-e414-11ea-86dd-52d2f9412cdf.png)

**Comment by CristobalPenaloza** [comment]
Hi @Fabrix10. Thank you for telling me, I didn't knew that the Clone Hero devs had already added 5 line support!
I made a new version in my fork which separates the orange and greens buttons.

You can download it from here:
https://github.com/CristobalPenaloza/WiitarThing/releases/tag/v2.9

Let me know if you have any issues ;)

**Comment by Rirya** [comment]
@CristobalPenaloza with the new release now everything works perfectly fine, thank you man

**Comment by PipeRojas** [comment]
I can confirm that its now possible to use my Wii GHTW Drums. Im closing this issue, thanks guys
