### ISSUE TITLE
Wiidrums problem

### ISSUE THREAD

**Issue by elkyarypappa** [Meowmaritus/WiitarThing#6]
I dont know why my wii drums are not working with clone hero using wiitarthing, i have this exactly model. Clone hero doesnt detect when i press any button with the drums.
https://www.flickr.com/photos/pipilo/3246147737/

I already had install the wiitarthing before this update, so i just downloaded the last version of wiitarthing and tried.

![image](https://user-images.githubusercontent.com/65004065/81371755-f1e4b780-90b5-11ea-8fd7-1a9cfd0d82c2.png)
The program looks like this when i connect the drums, but the clone hero doesnt detect when i hit the drums.

Here's what i do:
1.- open wiitarthing in admin
2.- sync my wiimote already connected to the drums
3.- press connect to player 1.

Next, im seeing that the wiimote leds are still flashing when is already connected.
This does not happen with the guitar, when i press connect to player 1, the leds stop flashing and stands still in player 1 led.

When the wiimote is connected in player 1 in wiitarthing, i disconnect it from the drums and connect it to the guitar and works fine, the wiitarthing recognizes it rapidly and the led stands still in player 1, now i try backwards but nothing happens, just changes the program from guitar to drums

Tried to config the drums in clone hero but nothing happens

**Comment by elkyarypappa** [comment]
nvm it worked fine today

**Comment by clorl** [comment]
This isn't resolved for me. I tried to plug in the wiimote to the drums, Wiitar Thing does recognize the controller as a drum but no input is received.
